###Test sever: api/v1/index.js
GET http://localhost:3010/v1

########################################################################
#########     Products
########################################################################

### Products/ Get-all
GET http://localhost:3010/v1/products



### Products/ Comment and review 
PATCH http://localhost:3010/v1/product/review/637f1097749792376c0e2a08
Content-Type: application/json

{
    "name":"dien@gmail.com",
    "comment":"oke next"
}

###Product/:slug
GET http://localhost:3010/v1/product/textslug/Brad cafe ColdBrew  Navite

###Product/:slug
GET http://localhost:3010/v1/product/slug/Brad cafe ColdBrew  Navite

###Product/:id
GET http://localhost:3010/v1/product/635e5477ee5e5c5968c703f1


###########################
########## PRODUCT/CATEGORY
### Products/ Category side bar
GET http://localhost:3010/v1/Category-sideBar

###
GET http://localhost:3010/v1/Category-sideBar/category/combo


### Products/ Get-by-category for combo
GET http://localhost:3010/v1/Category-combo

### Products/ Get-by-category for single
GET http://localhost:3010/v1/Category-single


### Orders/ Get-by-status
GET http://localhost:3010/v1/homePage/rollTop
Content-Type: application/json

########################################################################
########## END
########################################################################

########################################################################
########## ORDERS
########################################################################

### lấy tất cả order ra theo người mua
GET http://localhost:3010/v1/History-orders-by-user

###
Get http://localhost:3010/v1/History-orders

###
Get http://localhost:3010/v1/orders/text


###   
GET http://localhost:3010/v1/upload

### Products/ Get-history-orders
GET http://localhost:3010/v1/History-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxNGMyMmMyYmZjMWJmNDY5MzQ0ZDkiLCJyb2xlSWQiOiJ1c2VyIiwiaWF0IjoxNjY3Mzc0Mjc0fQ.rM293__jvGGye3IZYsnkUjxqVnvuifvncq9T05_KTVI


###
GET http://localhost:3010/v1/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxNGMyMmMyYmZjMWJmNDY5MzQ0ZDkiLCJyb2xlSWQiOiJ1c2VyIiwiaWF0IjoxNjY3Mzk3MjgzfQ.tXN_cmReqOoq2sm0xZQQ4F3dQkFGXrNELka-oiLrZf8

###
POST http://localhost:3010/v1/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzVmYTE2OWNjYzc5ZmU1NmJkODk2NmIiLCJpYXQiOjE2NjcyMTIxNjl9.yLzzd77VjMid--40W8BW9NKx16_su0E17TWgiRpJ00I

{
    "user":"dien@gmail.com"
}

########################################################################
########## Login
########################################################################

### LOGIN/admin
POST http://localhost:3010/v1/login
Content-Type: application/json

{
    "email": "dien@gmail.com",
    "password": "123"
}

###LOGIN/user
POST http://localhost:3010/v1/login
Content-Type: application/json

{
    "email": "dien05022002@gmail.com",
    "password": "123"
}

### REGISTER
POST http://localhost:3010/v1/register
Content-Type: application/json

{
    "name": "dien",
    "password": "123",
    "email": "dien05022002@gmail.com",
    "roleId": "user"
    
}


########################################################################
########## ADMIN/user
########################################################################

### getAll
GET http://localhost:3010/v1/getAllUsers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxNGJjYmQxZWIyNjVjNTQ4N2E0OTEiLCJyb2xlSWQiOiJhZG1pbiIsImlhdCI6MTY2NzgzMDM3Nn0.SxOvSetkVdr48m6tyHkvIn9ifhGRPKeQlPVGrCOLwp4



### text verifyAdim
GET http://localhost:3010/v1/getAllUsers/text
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxM2JiNjc4M2MzYTE2ODBlYTc4ZjIiLCJyb2xlSWQiOiJhZG1pbiIsImlhdCI6MTY2NzMyMjk4MX0.D2IkgEEXs6ro69sAnCoTkEjFBzsRWIAYQe3k3M_4eck

### getById
GET http://localhost:3010/v1/getUsers/63614bcbd1eb265c5487a491
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxNGJjYmQxZWIyNjVjNTQ4N2E0OTEiLCJyb2xlSWQiOiJhZG1pbiIsImlhdCI6MTY2ODc2MjU5Mn0.RjlTVh9yGp0Ae4lxnzQzRnVG7xsiqeD7GdSZkctfxbU

### updataUser
PATCH  http://localhost:3010/v1/updataUsers/63613bb6783c3a1680ea78f2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxM2JiNjc4M2MzYTE2ODBlYTc4ZjIiLCJyb2xlSWQiOiJhZG1pbiIsImlhdCI6MTY2NzM0OTQ4NX0.oKMSBxioWgp6dsrvJl7GsUIawtdyzLg2bT06bVDjtko

{
    "name": "dien1234",
    "password": "123",
    "email": "dien1234@gmail.com",
    "roleId": "user"
    
}

### updataUser
PATCH  http://localhost:3010/v1/updataUsers/63614bcbd1eb265c5487a491

{
    "name": "dien0502",
    "password": "123",
    "email": "dien05022002@gmail.com",
    "roleId": "user"
    
}

########################################################################
########## ADMIN/Products
### Products/ Get-all
GET http://localhost:3010/v1/admin/getProducts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxNGJjYmQxZWIyNjVjNTQ4N2E0OTEiLCJyb2xlSWQiOiJhZG1pbiIsImlhdCI6MTY2Nzg4MjI0MX0.EJdQr_7TywaO6Iu-0-V8AF1PlM-7B9KMIBBDoCYE9nU


### Products/ Get-byId
GET http://localhost:3010/v1/admin/getByIdProducts/6361cf23415046d812ce6d39
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxNGJjYmQxZWIyNjVjNTQ4N2E0OTEiLCJyb2xlSWQiOiJhZG1pbiIsImlhdCI6MTY2ODc2MjU5Mn0.RjlTVh9yGp0Ae4lxnzQzRnVG7xsiqeD7GdSZkctfxbU


### Products/ Get-byId
DELETE  http://localhost:3010/v1/admin/deleteProduct/636a077bca6d2df9bfe095e8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxNGJjYmQxZWIyNjVjNTQ4N2E0OTEiLCJyb2xlSWQiOiJhZG1pbiIsImlhdCI6MTY2ODc3OTI2MX0.VqJKzS1BhgI-H8bIkdeEgMLXKhank1gksej7qnszYRM


########################################################################
########## ADMIN/Orders
### Orders/ Get-all
GET http://localhost:3010/v1/admin/getAllOrders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxNGJjYmQxZWIyNjVjNTQ4N2E0OTEiLCJyb2xlSWQiOiJhZG1pbiIsImlhdCI6MTY2ODk1NDgzMn0.Uu6UnwOgTKQSz9_DaSpGI_DBwlAv98oWD_ZxRKvSD_A


### Orders/ Get-byId
GET http://localhost:3010/v1/admin/getOrderById/637a25d2599ae51a235b9be9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzYxNGJjYmQxZWIyNjVjNTQ4N2E0OTEiLCJyb2xlSWQiOiJhZG1pbiIsImlhdCI6MTY2ODk1NDgzMn0.Uu6UnwOgTKQSz9_DaSpGI_DBwlAv98oWD_ZxRKvSD_A


### Orders/ Get-byId
PATCH http://localhost:3010/v1/admin/textOrder/6360cddce36a5d62fbe358b9
Content-Type: application/json

{
    "isPaid": false,
    "isDelivered": true
}

### Orders/ Get-byId
GET http://localhost:3010/v1/admin/getAllOrdersToday
Content-Type: application/json


